"""orderproduct price to float

Revision ID: 3814a8196050
Revises: 909b640630cd
Create Date: 2026-06-24 12:58:17.401690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3814a8196050'
down_revision: Union[str, Sequence[str], None] = '909b640630cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderproducts', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using='price::double precision')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderproducts', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='price::integer')
    # ### end Alembic commands ###
