"""add permissions

Revision ID: 4e8448952e59
Revises: 0e8f6121bbfc
Create Date: 2026-01-08 12:31:01.190291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e8448952e59"
down_revision: Union[str, Sequence[str], None] = "0e8f6121bbfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "permissions",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{CAN_SELF_DELETE}'::text[]"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "permissions")
    # ### end Alembic commands ###
