"""use token since

Revision ID: d5eb2d79479a
Revises: 4e8448952e59
Create Date: 2026-01-09 10:03:37.982959

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5eb2d79479a"
down_revision: Union[str, Sequence[str], None] = "4e8448952e59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("use_token_since", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "use_token_since")
    # ### end Alembic commands ###
